UnitedBanking/Controllers/AuthController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using UnitedBanking.Context;
using UnitedBanking.Models;

namespace UnitedBanking.Controllers
{
    public class AuthController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        //private readonly ApplicationDbContext _context;

        private readonly SignInManager<IdentityUser> _signInManager;

        public AuthController(SignInManager<IdentityUser> signInManager, UserManager<IdentityUser> userManager)
        {
            _signInManager = signInManager;
            _userManager = userManager;
        }


        public IActionResult Login()
        {
            return View();
        }

        public IActionResult Signup()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult>Signup(RegisterViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);

            }

            if (model.Password != model.ConfirmPassword)
            {
                ModelState.AddModelError("", "The password and confirmation password do not match.");
                return View(model); // Return with an error if the passwords don't match
            }


            var user=new IdentityUser { UserName=model.Username, Email=model.Email};
            var result=await _userManager.CreateAsync(user,model.Password);

            if (result.Succeeded)
            {
                await _userManager.AddToRoleAsync(user, "Customer");
                await _signInManager.SignInAsync(user, isPersistent: false);
                return RedirectToAction("Index", "Home"); // Redirect to home page
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description); // Add errors to the model state
            }

            return View(model); // Return the view with the errors
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("Login", model);
            }

            var result = await _signInManager.PasswordSignInAsync(model.Username, model.Password, false, false);
            if (result.Succeeded)
                return RedirectToAction("Index", "Home");
            ModelState.AddModelError("", "Your Username or Password is Incorrect");
            return View("Login", model);
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
            
    }
}

UnitedBanking/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UnitedBanking.Context;
using UnitedBanking.Models;

namespace UnitedBanking.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EmployeesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Employees
        public async Task<IActionResult> Index()
        {
            return View(await _context.Employees.ToListAsync());
        }

        // GET: Employees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employees = await _context.Employees
                .FirstOrDefaultAsync(m => m.ID == id);
            if (employees == null)
            {
                return NotFound();
            }

            return View(employees);
        }

        // GET: Employees/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Salary,Position,Age,Gender,FirstName,LastName,Role")] Employees employees)
        {
            if (ModelState.IsValid)
            {
                _context.Add(employees);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(employees);
        }

        // GET: Employees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employees = await _context.Employees.FindAsync(id);
            if (employees == null)
            {
                return NotFound();
            }
            return View(employees);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Salary,Position,Age,Gender,FirstName,LastName,Role")] Employees employees)
        {
            if (id != employees.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employees);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeesExists(employees.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(employees);
        }

        // GET: Employees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employees = await _context.Employees
                .FirstOrDefaultAsync(m => m.ID == id);
            if (employees == null)
            {
                return NotFound();
            }

            return View(employees);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var employees = await _context.Employees.FindAsync(id);
            if (employees != null)
            {
                _context.Employees.Remove(employees);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmployeesExists(int id)
        {
            return _context.Employees.Any(e => e.ID == id);
        }
    }
}

UnitedBanking/Views/Shared/_AccountSidebar.cshtml
@{
    Layout = "_Layout";
}

<div class="grid-container-account">
    <nav class="profilesidebar">
        <h2>Account</h2>
        <ul>
            <li><a asp-controller="Account" asp-action="Profile">Profile</a></li>
            <li><a asp-controller="Account" asp-action="Balance">Balance</a></li>
            <li> <a href="#">Transactions</a></li>
            <li><a href="#">Settings</a></li>
        </ul>
        <form asp-controller="Auth" asp-action="Logout" method="post">
            <button type="submit" class="btn btn-danger">Logout</button>
        </form>
    </nav>

    <div class="main-account">
        @RenderBody()
    </div>


</div>

UnitedBanking/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UnitedBanking</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UnitedBanking.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
</head>
<body>   
    <div class="grid-container">
        <div class="header">
            <nav class="navbar navbar-expand-lg custom-navbar border-bottom box-shadow ">
                <div class="container-fluid">
                    <a class="navbar-brand ms-5 text-custom-color" asp-area="" asp-controller="Home" asp-action="Index"><i class="fa-solid fa-feather-pointed fa-icon"></i> UnitedBanking</a>

                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">                  
                        <i class="fa-solid fa-bars"></i>
                    </button>

                    <div class="collapse navbar-collapse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item dropdown ms-4">
                                <span class="nav-link dropdown-toggle text-custom-color">Financing</span>                          
                                <ul class="dropdown-menu" aria-labelledby="financingDropdown">
                                    <li class="title">Credit Cards</li>
                                    <hr />
                                    <li><a class="dropdown-item" href="#">Retail Credit Cards</a></li>
                                    <li><a class="dropdown-item" href="#">UB MasterCard</a></li>
                                    <li><a class="dropdown-item" href="#">UB Sport</a></li>
                                </ul>
                            </li>
                                                      
                                <li class="nav-item dropdown ms-4">
                                    <span class="nav-link dropdown-toggle text-custom-color">Banking </span>
                                    <ul class="dropdown-menu" aria-labelledby="BankingDropdown">
                                        <li class="title">Savings</li>
                                        <hr />  
                                        <li><a class="dropdown-item" href="#">IRAs</a></li>
                                        <li><a class="dropdown-item" href="#">CDs</a></li>
                                        <li><a class="dropdown-item" href="#">Money Markets</a></li>
                                        <li><a class="dropdown-item" href="#">Online Banking</a></li>
                                        <li><a class="dropdown-item" href="#">Mobile Banking</a></li>
                                    </ul>
                                </li>
                            @* @if (User.Identity.IsAuthenticated && (User.IsInRole("Admin")))
                            {
                            <li class="nav-item ms-4"><a class="nav-link text-custom-color navbar-link-custom" asp-area="" asp-controller="Employees" asp-action="Index" a>Employees</a></li>
                            } *@
                            <li class="nav-item ms-4"><a class="nav-link text-custom-color navbar-link-custom" style="cursor: pointer !important" asp-area="" asp-controller="Employees" asp-action="Index" a>Employees</a></li>
                        </ul>

                        <ul class="navbar-nav ms-auto">
                            <li class="nav-item dropdown ms-4">
                                <span class="nav-link dropdown-toggle text-custom-color">Help</span>
                                <ul class="dropdown-menu dropdown-custom" aria-labelledby="HelpDropdown">
                                    <li><a class="dropdown-item" href="#">Contact Us</a></li>
                                    <li><a class="dropdown-item" href="#">Fraud Center</a></li>
                                    <li><a class="dropdown-item" href="#">Common Issues</a></li>
                                </ul>
                            </li>

                            <li class="nav-item dropdown ms-4">
                                <span class="nav-link dropdown-toggle text-custom-color">About Us</span>
                                <ul class="dropdown-menu dropdown-custom" aria-labelledby="AboutDropdown">
                                    <li><a class="dropdown-item" href="#">Work For Us</a></li>
                                    <li><a class="dropdown-item" href="#">Why UnitedBanking</a></li>
                                    <li><a class="dropdown-item" href="#">About Our Company</a></li>
                                </ul>
                            </li>

                            @if (!User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item ms-4"><button class="nav-link btn btn-custom text-nowrap" onclick="location.href='@Url.Action("Login", "Auth")'">Login <i class="fa-solid fa-user"></i></li>
                            }

                            @if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item dropdown ms-4">
                                    <a asp-controller="Account" asp-action="Profile" class="nav-link text-custom-color navbar-link-custom"><i class="fa-solid fa-circle-user profile-icon"></i></a>
                                </li>
                            }                         
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
     

        <div class="main">
            @RenderBody()
        </div>


        <footer class="footer">
            &copy; 2025 - UnitedBanking - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </footer>

    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>